### ISSUE TITLE
feature request: add/subtract Number as well as {Integer|Float}Variable

### ISSUE THREAD

**Issue by craftingcoder** [relimited/Craftjs#8]
I've been finding myself often making an IntegerVariable and constraining it to equal a constant just so I can use it in an add or subtract expression. Moving that into the library would be nice!

**Comment by relimited** [comment]
The FloatVariable version of this just passed its units tests today!  After I port the logic to all ops (not just + and -, but \* and / and ^ and whatever else this library does) and over to Integers, the new way to call will look like:
`FloatVariable.add({Number | FloatVariable}, {Number | FloatVariable});`

Numbers will be treated like constants, and errors get thrown if you try to have a Number for both operands.  Mixing FloatVariable and IntegerVariables in equations is still a ways off, for now.  :+1:

**Comment by relimited** [comment]
This feature is now in version 0.22
